//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prak5_service_lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customerSet()
        {
            this.orderSets = new HashSet<orderSet>();
        }
    
        public int Id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public double balance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderSet> orderSets { get; set; }
    }
}
