//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prak5_service_lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderLineSet
    {
        public int Id { get; set; }
        public int amount { get; set; }
        public int order_Id { get; set; }
        public int product_Id { get; set; }
    
        public virtual orderSet orderSet { get; set; }
        public virtual productSet productSet { get; set; }
    }
}
