//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practicum_5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class prac5_dbEntities : DbContext
    {
        public prac5_dbEntities()
            : base("name=prac5_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customerSet> customerSets { get; set; }
        public virtual DbSet<orderLineSet> orderLineSets { get; set; }
        public virtual DbSet<orderSet> orderSets { get; set; }
        public virtual DbSet<productSet> productSets { get; set; }
        public virtual DbSet<storeSet> storeSets { get; set; }
    }
}
